blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/aidevme/pcf-syntax-highlighter/blob/main/README.md
    about: Read the project documentation before opening an issue.
