/**
 * Theme definitions for syntax highlighting
 * Maps theme IDs to human-readable display names
 */
export const themes: Record<string, string> = {
  'andromeda': 'Andromeda',
  'ayu-dark': 'Ayu Dark',
  'ayu-mirage': 'Ayu Mirage',
  'ayu-light': 'Ayu Light',
  'cobalt2': 'Cobalt2',
  'dark-plus': 'Dark Plus',
  'dracula-soft': 'Dracula Soft',
  'dracula': 'Dracula',
  'github-dark-dimmed': 'GitHub Dark Dimmed',
  'github-dark': 'GitHub Dark',
  'github-light': 'GitHub Light',
  'light-plus': 'Light Plus',
  'material-theme-darker': 'Material Theme Darker',
  'material-theme': 'Material Theme',
  'material-theme-lighter': 'Material Theme Lighter',
  'material-theme-ocean': 'Material Theme Ocean',
  'material-theme-palenight': 'Material Theme Palenight',
  'min-dark': 'Min Dark',
  'min-light': 'Min Light',
  'monokai': 'Monokai',
  'night-owl': 'Night Owl',
  'nord': 'Nord',
  'one-dark-pro': 'One Dark Pro',
  'poimandres': 'Poimandres',
  'rose-pine': 'Rosé Pine',
  'rose-pine-dawn': 'Rosé Pine Dawn',
  'rose-pine-moon': 'Rosé Pine Moon',
  'slack-dark': 'Slack Dark',
  'slack-ochin': 'Slack Ochin',
  'solarized-dark': 'Solarized Dark',
  'solarized-light': 'Solarized Light',
  'vitesse-dark': 'Vitesse Dark',
  'vitesse-light': 'Vitesse Light',
};
